<?php

use Illuminate\Database\Seeder;

class SettingMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('setting_menus')->insert([
            [
                'MENU_NAME'=>'New_Customer_List',
                'LEVEL_TMR'=>1,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>0,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Schedule_Customer_List',
                'LEVEL_TMR'=>1,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>0,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Other_Customer_List',
                'LEVEL_TMR'=>1,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>0,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'QA_Customer_List',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>1,
                'LEVEL_SPVQA'=>1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Recording_CALL_LOG',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>1,
                'LEVEL_SPVQA'=>1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Report',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>1,
                'LEVEL_SPVQA'=>1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],

            [
                'MENU_NAME'=>'Print_Management',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],

            [
                'MENU_NAME'=>'Upload_And_Distribution_Data',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Setting_Progressive',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'User Management',
                'MENU_LINK'=>'/account',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Voucher',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'New_Data_Authorization',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Database_Maintenance',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Setting_Menu',
                'MENU_LINK'=>'/setting-menu',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>0,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Product_Setup',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>0,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Change_Password',
                'MENU_LINK'=>'/profile',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Performance_Monitoring',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Inbound_Follow_Up_List',
                'LEVEL_TMR'=>1,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>0,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Inbound_Screen',
                'LEVEL_TMR'=>1,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>0,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Dashboard',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Setting_Target',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>0,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Setting_Date',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>0,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Activity_Monitoring',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],

            [
                'MENU_NAME'=>'Self_Monitoring',
                'LEVEL_TMR'=>1,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>1,
                'LEVEL_QA'=>1,
                'LEVEL_SPVQA'=>1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'Setting_Paramter',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>0,
                'LEVEL_ATM'=>1,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'MENU_NAME'=>'SPV_Customer_LIST',
                'LEVEL_TMR'=>0,
                'LEVEL_SPV'=>1,
                'LEVEL_ATM'=>0,
                'LEVEL_ADMIN'=>0,
                'LEVEL_QA'=>0,
                'LEVEL_SPVQA'=>0,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],

        ]);
    }
}
