CREATE TABLE `DUPLICATE_DATA`(
ID bigint PRIMARY KEY NOT NULL,
CUST_APPID_EXIST bigint NULL,
CUST_NAME varchar(500) NULL,
CAMPAIGN_NAME varchar(500) NULL,
PRODUCT_NAME varchar(500) NULL,
CUST_TYPE varchar(500) NULL,
CUST_TYPE_DETAIL varchar(500) NULL,
DATA_CARD_TYPE varchar(500) NULL,
CUST_PHONE1 varchar(500) NULL,
RESULT_DETAIL varchar(500) NULL,
UPLOAD_DATE datetime NULL,
DUPLICATE_TYPE varchar(50) NULL
);


CREATE TABLE `MASTER_BLACKLIST_NUMBER`(
ID bigint PRIMARY KEY NOT NULL,
CONTACT_NUMBER varchar(50) NULL,
NAME varchar(50) NULL,
STATUS varchar(50) NULL,
REMARKS varchar(100) NULL
);


CREATE TABLE MASTER_PARAM(
ID bigint PRIMARY KEY NOT NULL,
PARAM_AUTO varchar(50) NULL,
PARAM_VALUE varchar(50) NULL,
PARAM_REMARKS varchar(50) NULL,
LAST_UPDATE_DATE datetime NULL,
LAST_UPDATED_BY datetime NULL,
STATUS varchar(50) NULL);





CREATE TABLE `MASTER_DATA_CARD`(
ID_MASTER bigint PRIMARY KEY NOT NULL,
CIF_NUMBER varchar(50) NULL,
CARD_NAME varchar(100) NULL,
CARD_TYPE varchar(100) NULL,
CARD_NO varchar(100) NULL,
CARD_BANK varchar(100) NULL,
CARD_LIMIT varchar(100) NULL,
CARD_EXP varchar(50) NULL,
CARD_STATUS varchar(50) NULL,
LAST_UPDATE datetime NULL,
CUST_APPID varchar(50) NULL
);







DROP TABLE IF EXISTS `MASTER_USERID`;
CREATE TABLE `MASTER_USERID` (
ID_USER bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
USER_ID varchar(50) NULL ,
USER_NAME varchar(50) NULL ,
USER_PWD varchar(50) NULL ,
USER_LEVEL varchar(50) NULL ,
USER_DN varchar(50) NULL ,/* field tambah*/
USER_EXT varchar(50) NULL ,
USER_STATUS varchar(50) NULL ,
USER_TEAM varchar(20) NULL ,
USER_GROUP varchar(10) NULL ,
USER_LEADER varchar(10) NULL ,
USER_MANAGER varchar(50) NULL ,
USER_SPV varchar(50) NULL ,
TEAM_QA varchar(50) NULL ,
ID_MITRA varchar(50) NULL ,
AUTODIAL varchar(2) NULL ,
SOFTPHONE varchar(2) NULL ,
LAST_UPDATE datetime(0) NULL ,
PWD_EXPIRE datetime(0) NULL ,
DATE_JOIN datetime(0) NULL ,
DATE_RESIGN datetime(0) NULL ,
CREATE_USER varchar(50) NULL ,
EDIT_USER varchar(50) NULL ,
LOGIN_STATUS varchar(50) NULL ,
LOCK_STATUS varchar(50) NULL ,
LAST_ACCESS datetime(0) NULL ,
LAST_UPDATED_BY varchar(50) NULL ,
ISDELETED varchar(10) NULL ,
AGENT_PHOTO longblob NULL,
LEVEL_TARGET varchar(50) NULL ,
CREATE_DATE datetime(0) NULL ,
EDIT_DATE datetime(0) NULL ,
LOGIN_IP varchar(50) NULL ,
LOGIN_VERSION varchar(50) NULL
);


CREATE TABLE `master_user_agents` (
`id` bigint(20) UNSIGNED NOT NULL,
`AGENT_USERNAME` varchar(50) NOT NULL,
`AGENT_NAME` varchar(50) DEFAULT NULL,
`AGENT_PWD` varchar(255) NOT NULL,
`AGENT_LEVEL` varchar(20) DEFAULT NULL,
`AGENT_DN` varchar(15) DEFAULT NULL,
`AGENT_STATUS` varchar(20) DEFAULT NULL,
`AGENT_TIME` varchar(255) DEFAULT NULL,
`GROUP_ID` varchar(20) DEFAULT NULL,
`LEADER_ID` varchar(30) DEFAULT NULL,
`SPV_ID` varchar(30) DEFAULT NULL,
`MANAGER_ID` varchar(20) DEFAULT NULL,
`LAST_UPDATE` date DEFAULT NULL,
`STS_AUTODIAL` varchar(10) DEFAULT NULL,
`STS_AUDITORIAL` varchar(20) DEFAULT NULL,
`PWD_EXPIRE` date DEFAULT '2021-06-17',
`RUNNING_STATUS` varchar(255) DEFAULT NULL,
`DATE_JOIN` date DEFAULT NULL,
`DATE_RESIGN` date DEFAULT NULL,
`TEAM` varchar(20) DEFAULT 'TEAM 1',
`CREATE_USER` varchar(20) DEFAULT 'ADMIN',
`BALANCE_VOUCHER` varchar(20) DEFAULT 'NULL',
`EXPIRE_DATE` date DEFAULT NULL,
`AGENT_GROUP` varchar(30) DEFAULT 'NULL',
`LOGIN_STATUS` tinyint(1) DEFAULT 0,
`LOCK_STATUS` tinyint(1) DEFAULT 0,
`APPROVE_VOUCHER` varchar(30) DEFAULT 'NULL',
`TEAM_QA` varchar(30) DEFAULT 'NULL',
`CAN_USE_SOFTPHONE` tinyint(1) DEFAULT 0,
`LAST_ACCESS` datetime DEFAULT NULL,
`LAST_UPDATED_BY` datetime DEFAULT NULL,
`IS_DELETED` tinyint(1) DEFAULT 0,
`AGENT_PHOTO` varchar(255) DEFAULT NULL,
`LEVEL_TARGET` varchar(20) DEFAULT NULL,
`ID_MITRA` varchar(20) DEFAULT NULL,
`ID_MITRA_BNILIFE` varchar(255) DEFAULT NULL,
`CREATE_DATE` date DEFAULT NULL,
`EDIT_DATE` date DEFAULT NULL,
`SPONSOR` date DEFAULT NULL,
`PRODUCT` varchar(30) DEFAULT NULL,
`LOGIN_IP` varchar(255) DEFAULT NULL,
`BS_VERSION` varchar(30) DEFAULT 'Animates 04',
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL
);
